name: Build docker image

on:
  push:
    branches:
    - main

    tags:
    - '*'

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  grafana-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: '10.2.3'
        tags: 10.2.3,10.2,10,latest
